
//default value

var mode = "auto_detect" ;

var singleProxySetting = {
	singleProxy : {
		scheme:"socks5",
		host:"127.0.0.1",
		port:10808
	},
    bypass_list : [
		"localhost",
		"127.*",
		"10.*",
		"172.16.*",
		"172.17.*",
		"172.18.*",
		"172.19.*",
		"172.20.*",
		"172.21.*",
		"172.22.*",
		"172.23.*",
		"172.24.*",
		"172.25.*",
		"172.26.*",
		"172.27.*",
		"172.28.*",
		"172.29.*",
		"172.30.*",
		"172.31.*",
		"192.168.*",
		"*.12306.cn",
		"*.51ym.me",
		"*.52pojie.cn",
		"*.8686c.com",
		"*.abercrombie.com",
		"*.adobesc.com",
		"*.air-matters.com",
		"*.air-matters.io",
		"*.airtable.com",
		"*.akadns.net",
		"*.apache.org",
		"*.api.crisp.chat",
		"*.api.termius.com",
		"*.appshike.com",
		"*.appstore.com",
		"*.aweme.snssdk.com",
		"*.bababian.com",
		"*.battle.net",
		"*.beatsbydre.com",
		"*.bet365.com",
		"*.bilibili.cn",
		"*.ccgslb.com",
		"*.ccgslb.net",
		"*.chunbo.com",
		"*.chunboimg.com",
		"*.clashroyaleapp.com",
		"*.cloudsigma.com",
		"*.cloudxns.net",
		"*.cmfu.com",
		"*.culturedcode.com",
		"*.dct-cloud.com",
		"*.didialift.com",
		"*.douyutv.com",
		"*.duokan.com",
		"*.dytt8.net",
		"*.easou.com",
		"*.ecitic.net",
		"*.eclipse.org",
		"*.eudic.net",
		"*.ewqcxz.com",
		"*.fir.im",
		"*.frdic.com",
		"*.fresh-ideas.cc",
		"*.godic.net",
		"*.goodread.com",
		"*.haibian.com",
		"*.hdslb.net",
		"*.hollisterco.com",
		"*.hongxiu.com",
		"*.hxcdn.net",
		"*.images.unsplash.com",
		"*.img4me.com",
		"*.ipify.org",
		"*.ixdzs.com",
		"*.jd.hk",
		"*.jianshuapi.com",
		"*.jomodns.com",
		"*.jsboxbbs.com",
		"*.knewone.com",
		"*.kuaidi100.com",
		"*.lemicp.com",
		"*.letvcloud.com",
		"*.lizhi.io",
		"*.localizecdn.com",
		"*.lucifr.com",
		"*.luoo.net",
		"*.mai.tn",
		"*.maven.org",
		"*.miwifi.com",
		"*.moji.com",
		"*.moke.com",
		"*.mtalk.google.com",
		"*.mxhichina.com",
		"*.myqcloud.com",
		"*.myunlu.com",
		"*.netease.com",
		"*.nfoservers.com",
		"*.nssurge.com",
		"*.nuomi.com",
		"*.ourdvs.com",
		"*.overcast.fm",
		"*.paypal.com",
		"*.paypalobjects.com",
		"*.pgyer.com",
		"*.qdaily.com",
		"*.qdmm.com",
		"*.qin.io",
		"*.qingmang.me",
		"*.qingmang.mobi",
		"*.qqurl.com",
		"*.rarbg.to",
		"*.rrmj.tv",
		"*.ruguoapp.com",
		"*.sm.ms",
		"*.snwx.com",
		"*.soku.com",
		"*.startssl.com",
		"*.store.steampowered.com",
		"*.symcd.com",
		"*.teamviewer.com",
		"*.tmzvps.com",
		"*.trello.com",
		"*.trellocdn.com",
		"*.ttmeiju.com",
		"*.udache.com",
		"*.uxengine.net",
		"*.weather.bjango.com",
		"*.weather.com",
		"*.webqxs.com",
		"*.weico.cc",
		"*.wenku8.net",
		"*.werewolf.53site.com",
		"*.windowsupdate.com",
		"*.wkcdn.com",
		"*.workflowy.com",
		"*.xdrig.com",
		"*.xiaojukeji.com",
		"*.xiaomi.net",
		"*.xiaomicp.com",
		"*.ximalaya.com",
		"*.xitek.com",
		"*.xmcdn.com",
		"*.xslb.net",
		"*.xteko.com",
		"*.yach.me",
		"*.yixia.com",
		"*.yunjiasu-cdn.net",
		"*.zealer.com",
		"*.zgslb.net",
		"*.zimuzu.tv",
		"*.zmz002.com",
		"*.samsungdm.com"
	]
};

var multipleProxySetting = {

	proxyForHttpSetting : {
		scheme:"socks5",
		host:"127.0.0.1",
		port:10808
	},
	proxyForHttpsSetting : {
		scheme:"socks5",
		host:"127.0.0.1",
		port:10808
	},
	proxyForFtpSetting : {
		scheme:"socks5",
		host:"127.0.0.1",
		port:10808
	},
	fallbackProxySetting : {
		scheme:"socks5",
		host:"127.0.0.1",
		port:10808
	},
	multiple_proxy_bypass_list : [
		"localhost",
		"127.*",
		"10.*",
		"172.16.*",
		"172.17.*",
		"172.18.*",
		"172.19.*",
		"172.20.*",
		"172.21.*",
		"172.22.*",
		"172.23.*",
		"172.24.*",
		"172.25.*",
		"172.26.*",
		"172.27.*",
		"172.28.*",
		"172.29.*",
		"172.30.*",
		"172.31.*",
		"192.168.*",
		"*.12306.cn",
		"*.51ym.me",
		"*.52pojie.cn",
		"*.8686c.com",
		"*.abercrombie.com",
		"*.adobesc.com",
		"*.air-matters.com",
		"*.air-matters.io",
		"*.airtable.com",
		"*.akadns.net",
		"*.apache.org",
		"*.api.crisp.chat",
		"*.api.termius.com",
		"*.appshike.com",
		"*.appstore.com",
		"*.aweme.snssdk.com",
		"*.bababian.com",
		"*.battle.net",
		"*.beatsbydre.com",
		"*.bet365.com",
		"*.bilibili.cn",
		"*.ccgslb.com",
		"*.ccgslb.net",
		"*.chunbo.com",
		"*.chunboimg.com",
		"*.clashroyaleapp.com",
		"*.cloudsigma.com",
		"*.cloudxns.net",
		"*.cmfu.com",
		"*.culturedcode.com",
		"*.dct-cloud.com",
		"*.didialift.com",
		"*.douyutv.com",
		"*.duokan.com",
		"*.dytt8.net",
		"*.easou.com",
		"*.ecitic.net",
		"*.eclipse.org",
		"*.eudic.net",
		"*.ewqcxz.com",
		"*.fir.im",
		"*.frdic.com",
		"*.fresh-ideas.cc",
		"*.godic.net",
		"*.goodread.com",
		"*.haibian.com",
		"*.hdslb.net",
		"*.hollisterco.com",
		"*.hongxiu.com",
		"*.hxcdn.net",
		"*.images.unsplash.com",
		"*.img4me.com",
		"*.ipify.org",
		"*.ixdzs.com",
		"*.jd.hk",
		"*.jianshuapi.com",
		"*.jomodns.com",
		"*.jsboxbbs.com",
		"*.knewone.com",
		"*.kuaidi100.com",
		"*.lemicp.com",
		"*.letvcloud.com",
		"*.lizhi.io",
		"*.localizecdn.com",
		"*.lucifr.com",
		"*.luoo.net",
		"*.mai.tn",
		"*.maven.org",
		"*.miwifi.com",
		"*.moji.com",
		"*.moke.com",
		"*.mtalk.google.com",
		"*.mxhichina.com",
		"*.myqcloud.com",
		"*.myunlu.com",
		"*.netease.com",
		"*.nfoservers.com",
		"*.nssurge.com",
		"*.nuomi.com",
		"*.ourdvs.com",
		"*.overcast.fm",
		"*.paypal.com",
		"*.paypalobjects.com",
		"*.pgyer.com",
		"*.qdaily.com",
		"*.qdmm.com",
		"*.qin.io",
		"*.qingmang.me",
		"*.qingmang.mobi",
		"*.qqurl.com",
		"*.rarbg.to",
		"*.rrmj.tv",
		"*.ruguoapp.com",
		"*.sm.ms",
		"*.snwx.com",
		"*.soku.com",
		"*.startssl.com",
		"*.store.steampowered.com",
		"*.symcd.com",
		"*.teamviewer.com",
		"*.tmzvps.com",
		"*.trello.com",
		"*.trellocdn.com",
		"*.ttmeiju.com",
		"*.udache.com",
		"*.uxengine.net",
		"*.weather.bjango.com",
		"*.weather.com",
		"*.webqxs.com",
		"*.weico.cc",
		"*.wenku8.net",
		"*.werewolf.53site.com",
		"*.windowsupdate.com",
		"*.wkcdn.com",
		"*.workflowy.com",
		"*.xdrig.com",
		"*.xiaojukeji.com",
		"*.xiaomi.net",
		"*.xiaomicp.com",
		"*.ximalaya.com",
		"*.xitek.com",
		"*.xmcdn.com",
		"*.xslb.net",
		"*.xteko.com",
		"*.yach.me",
		"*.yixia.com",
		"*.yunjiasu-cdn.net",
		"*.zealer.com",
		"*.zgslb.net",
		"*.zimuzu.tv",
		"*.zmz002.com",
		"*.samsungdm.com"
	]
};

var URLToScript = "http://127.0.0.1:10002/proxy.pac"

var proxyScript = "function FindProxyForURL(url, host) {" +
"var bypassList = [" +
	"\"*.local\"," +
	"\"localhost\"," +
	"\"*.intranet.example.com\"," +
	"\"10.0.0.0/8\"," +
	"\"172.16.0.0/12\"," +
	"\"192.168.0.0/16\"" +
"];" +

"for (var i = 0; i < bypassList.length; i++) {" +
	"if (shExpMatch(host, bypassList[i]) || dnsDomainIs(host, bypassList[i])) {" +
		"return \"DIRECT\";" +
	"}" +
"}" +

"if (isInNet(dnsResolve(host), \"10.0.0.0\", \"255.0.0.0\") ||" +
	"isInNet(dnsResolve(host), \"172.16.0.0\", \"255.240.0.0\") ||" +
	"isInNet(dnsResolve(host), \"192.168.0.0\", \"255.255.0.0\")) {" +
	"return \"DIRECT\";" +
"}" +
"return \"SYSTEM\";" + // 更改为 DIRECT 或者 指定一个具体的代理服务器地址
"}";


